"""create_jobs_table

Revision ID: 37e16ecef223
Revises: a2f7b3c8d901
Create Date: 2026-02-01 09:15:25.050307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37e16ecef223'
down_revision: Union[str, None] = 'a2f7b3c8d901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('job_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("job_type IN ('train', 'predict', 'backtest')", name='ck_job_valid_type'),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed', 'cancelled')", name='ck_job_valid_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_job_id'), 'job', ['job_id'], unique=True)
    op.create_index(op.f('ix_job_job_type'), 'job', ['job_type'], unique=False)
    op.create_index('ix_job_params_gin', 'job', ['params'], unique=False, postgresql_using='gin')
    op.create_index('ix_job_result_gin', 'job', ['result'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_job_run_id'), 'job', ['run_id'], unique=False)
    op.create_index(op.f('ix_job_status'), 'job', ['status'], unique=False)
    op.create_index('ix_job_type_status', 'job', ['job_type', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_type_status', table_name='job')
    op.drop_index(op.f('ix_job_status'), table_name='job')
    op.drop_index(op.f('ix_job_run_id'), table_name='job')
    op.drop_index('ix_job_result_gin', table_name='job', postgresql_using='gin')
    op.drop_index('ix_job_params_gin', table_name='job', postgresql_using='gin')
    op.drop_index(op.f('ix_job_job_type'), table_name='job')
    op.drop_index(op.f('ix_job_job_id'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
