import { Checkbox } from '@/components/ui/checkbox'
import { Button } from '@/components/ui/button'
import { StatusBadge } from '@/components/common/status-badge'
import {
  labelForGroup,
  labelForSafetyClass,
  safetyClassChipVariant,
} from '@/lib/feature-frame-utils'
import type { FeatureGroup, FeatureSafetyClass } from '@/types/api'

/**
 * PRP-37 Slice C — V2 feature-pack toggle group. Renders one Checkbox per
 * available group; an optional safety chip per row when
 * `feature_safety_classes` is supplied on the metadata response.
 */

interface FeatureGroupsToggleProps {
  value: FeatureGroup[]
  onChange: (groups: FeatureGroup[]) => void
  availableGroups: FeatureGroup[]
  defaults: FeatureGroup[]
  safetyClasses?: Record<string, FeatureSafetyClass>
  disabled?: boolean
  className?: string
}

export function FeatureGroupsToggle({
  value,
  onChange,
  availableGroups,
  defaults,
  safetyClasses,
  disabled,
  className,
}: FeatureGroupsToggleProps) {
  function toggle(group: FeatureGroup, checked: boolean) {
    if (disabled) return
    const next = checked
      ? Array.from(new Set([...value, group]))
      : value.filter((g) => g !== group)
    onChange(next)
  }

  function applyDefaults() {
    if (disabled) return
    onChange(defaults.filter((g) => availableGroups.includes(g)))
  }

  function clearAll() {
    if (disabled) return
    onChange([])
  }

  return (
    <div
      className={`space-y-2 ${className ?? ''}`}
      data-testid="feature-groups-toggle"
    >
      <div className="flex flex-wrap items-center gap-2">
        <span className="text-muted-foreground text-xs">Feature packs</span>
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={applyDefaults}
          disabled={disabled || availableGroups.length === 0}
          data-testid="feature-groups-use-defaults"
        >
          Use defaults
        </Button>
        <Button
          type="button"
          variant="ghost"
          size="sm"
          onClick={clearAll}
          disabled={disabled || value.length === 0}
          data-testid="feature-groups-clear"
        >
          Clear
        </Button>
      </div>
      <ul className="grid grid-cols-1 gap-1.5 sm:grid-cols-2">
        {availableGroups.map((group) => {
          const checked = value.includes(group)
          // Surface the *most concerning* safety class across the group's
          // columns — if the operator sees an "error" chip, the group needs
          // supplied data; an absent chip means safety_classes was not
          // returned (older metadata) and we render no chip rather than
          // guessing.
          const safety = safetyForGroup(group, safetyClasses)
          return (
            <li
              key={group}
              className="flex items-center gap-2 rounded-md border px-2 py-1.5"
              data-testid={`feature-groups-row-${group}`}
            >
              <Checkbox
                checked={checked}
                disabled={disabled}
                onCheckedChange={(state) => toggle(group, state === true)}
                aria-label={labelForGroup(group)}
              />
              <span className="text-sm flex-1">{labelForGroup(group)}</span>
              {safety && (
                <StatusBadge variant={safetyClassChipVariant(safety)}>
                  {labelForSafetyClass(safety)}
                </StatusBadge>
              )}
            </li>
          )
        })}
      </ul>
      {availableGroups.length === 0 && (
        <p className="text-muted-foreground text-xs">
          No feature groups exposed by the server for this run.
        </p>
      )}
    </div>
  )
}

function safetyForGroup(
  group: FeatureGroup,
  safetyClasses: Record<string, FeatureSafetyClass> | undefined,
): FeatureSafetyClass | undefined {
  if (!safetyClasses) return undefined
  // group → column-name convention: every feature column generated by a
  // group starts with the group name (e.g. `target_history__lag_7`,
  // `inventory__on_hand_qty`). Match on prefix so we surface the worst
  // safety class found among the group's columns.
  const prefix = `${group}__`
  const matched = Object.entries(safetyClasses).filter(([col]) =>
    col.startsWith(prefix),
  )
  if (matched.length === 0) return undefined
  const order: FeatureSafetyClass[] = [
    'safe',
    'conditionally_safe',
    'unsafe_unless_supplied',
  ]
  let worst: FeatureSafetyClass = 'safe'
  for (const [, cls] of matched) {
    if (order.indexOf(cls) > order.indexOf(worst)) {
      worst = cls
    }
  }
  return worst
}
